# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2


jobs:
  build:
    docker: &docker_image
      - image: circleci/python:3.7-stretch-browsers

    steps:
      - checkout
      
      - run:
          name: install package and dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install .
            pip install pytest flake8

      - run:
          name: tests
          command: |
            . venv/bin/activate
            pytest

      - run:
          name: flake8
          command: |
            . venv/bin/activate
            flake8
